//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab04_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public string StudentID { get; set; }
        public string StudentName { get; set; }
        public double AverageScore { get; set; }
        public int FacultyID { get; set; }
    
        public virtual Faculty Faculty { get; set; }
    }
}
